dbt_airflow_project:
  outputs:
    dev:
      dataset: proj_test_data
      job_execution_timeout_seconds: 200
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dbt-airflow-linkage
      threads: 4
      type: bigquery
  target: dev
